print('sunqi')
print('newadd')
print('git diff file name')
print('git add filename')
print('git status filename')
print('git commit -m')
print('git log')
print('git log --pretty=oneline')
print('git reflog')
print('git reset --hard HEAD^')
print('git reset --hard commit_id')
print('git checkout -- filename')
print('git rm filename;git commit -m ')
