print('sunqi')
print('newadd')
print('git diff file name')
print('git add filename')
print('git status filename')
print('git commit -m')
print('git log')
print('git log --pretty=oneline')
print('git reflog')
print('git reset --hard HEAD^')
print('git reset --hard commit_id')
print('git checkout -- filename')
print('git rm filename;git commit -m ')
print()
print('github')
print('git remote add origin git@github.com:sq08201329/gitStroe.git')
print('git push -u origin master')
print('git clone git@github.com:sq08201329/gitStroe.git')
print()
print('git checkout -b branchname')
print('git checkout branchname')
print('git branch branchname')
print('git merge branchname')
feature1 and  featrue2
